version: "3.1"
services:
  web:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ge.4lSdGRl#@rewkm"
      WORDPRESS_DB_NAME: my-wpdb
    depends_on:
      - mysql
    volumes:
      - ./wordpress:/var/www/html
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ge.4lSdGRl#@rewkm"
      MYSQL_DATABASE: my-wpdb
  composer:
    image: composer:latest
    volumes:
      - ./wordpress:/app
    working_dir: /app
